Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2020-12, with the labels that each got.

#48 Add setting `client.DomainID` for domain-scoped token
  openstack/client.go
Labels: gate

#50 Remove default region value
  openstack/utils/utils.go
Labels: bug, gate

#51 LbaasV2 certificate update
  acceptance/openstack/networking/v2/extensions/lbaas_v2/certificates_test.go
  acceptance/openstack/networking/v2/extensions/vpnaas/ikepolicies_test.go
  openstack/networking/v2/extensions/lbaas_v2/certificates/requests.go
  openstack/networking/v2/extensions/lbaas_v2/certificates/results.go
Labels: gate

#55 Fix agency name yaml attribute
  openstack/loader.go
Labels: bug, gate

#57 Fix yaml file loading order
  openstack/loader.go
Labels: gate

#59 Make `auth_type` always taken in account
  openstack/loader.go
Labels: gate

#60 Add missing CSS client
  openstack/client.go
Labels: gate

#61 Minor refactoring of service catalog
  acceptance/openstack/identity/v3/catalog_test.go
  openstack/identity/v3/catalog/results.go
  openstack/identity/v3/catalog/testing/catalog_test.go
  openstack/identity/v3/catalog/testing/fixtures.go
  openstack/identity/v3/catalog/urls.go
Labels: gate

#63 Move all clients to use `Env`
  acceptance/clients/clients.go
  acceptance/openstack/csbs/v1/policies_test.go
  acceptance/openstack/dds/v3/flavors_test.go
  acceptance/openstack/dds/v3/instances_test.go
  acceptance/openstack/rds/v3/rds_test.go
Labels: gate

#62 Backport gophercloud/gophercloud#1766
  openstack/endpoint_location.go
Labels: gate

#65 Add unit tests to CI pipelines
  .zuul.yaml
  Makefile
  openstack/identity/v3/users/testing/fixtures.go
  openstack/testing/client_test.go
  openstack/testing/endpoint_location_test.go
  openstack/vpc/v1/bandwidths/testing/requests_test.go
Labels: gate

#66 Implement `cbr/v3/policies`
  acceptance/clients/clients.go
  acceptance/openstack/cbr/v3/policies_test.go
  openstack/cbr/v3/policies/requests.go
  openstack/cbr/v3/policies/results.go
  openstack/cbr/v3/policies/testing/fixtures.go
  openstack/cbr/v3/policies/testing/requests_test.go
  openstack/cbr/v3/policies/urls.go
  openstack/client.go
Labels: enhancement, gate

#67 Add new unit tests
  openstack/cbr/v3/policies/testing/fixtures.go
  openstack/cbr/v3/policies/testing/requests_test.go
Labels: gate

#68 Implement CBR tasks
  acceptance/openstack/cbr/v3/tasks_test.go
  acceptance/openstack/rds/v3/rds_test.go
  openstack/cbr/v3/tasks/requests.go
  openstack/cbr/v3/tasks/results.go
  openstack/cbr/v3/tasks/urls.go
Labels: gate

#34 Add Update functionality for CCE v3 addons
  acceptance/clients/clients.go
  acceptance/openstack/cce/v3/addons_test.go
  openstack/cce/v3/addons/requests.go
  openstack/cce/v3/addons/results.go
  openstack/cce/v3/addons/urls.go
Labels: enhancement, gate

#69 Cleanup go.mod file
  go.mod
  go.sum
Labels: gate

#71 Add acceptance tests
  .zuul.yaml
  Makefile
  acceptance/clients/clients.go
  acceptance/openstack/client_test.go
  acceptance/openstack/csbs/v1/policies_test.go
  acceptance/openstack/dds/v3/flavors_test.go
  acceptance/openstack/dds/v3/instances_test.go
  acceptance/openstack/networking/v1/helpers.go
  acceptance/openstack/networking/v1/subnet_test.go
  acceptance/openstack/networking/v2/peering/peerings.go
  acceptance/openstack/rds/v3/rds_test.go
  openstack/loader.go
  openstack/utils/utils.go
Labels: gate
