Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2022-12, with the labels that each got.

#476 [AS] rollback metadata typing in disk configuration
  acceptance/openstack/autoscaling/helpers.go
  openstack/autoscaling/v1/configurations/get.go
Labels: bug, gate

#477 Add retry for TooManyRequests error
  acceptance/openstack/client_test.go
  acceptance/openstack/networking/v2/sgs/sg_test.go
  provider_client.go
Labels: gate, post

#481 [CSS]: Fix `ExtendCluster` usage with special opts
  acceptance/openstack/css/v1/clusters_test.go
  openstack/css/v1/clusters/ExtendCluster.go
  openstack/css/v1/clusters/util.go
Labels: gate

#482 [throttling] fixed creation of go routines
  acceptance/openstack/networking/v2/sgs/sg_test.go
Labels: bug, gate

#485 [RDS]: Remove job % output and increase sleep time
  openstack/rds/v3/instances/job.go
Labels: gate

#486 [DDS]: Refactoring and new features
  acceptance/openstack/dds/v3/flavors_test.go
  acceptance/openstack/dds/v3/instances_test.go
  openstack/dds/v3/connection/KillSessions.go
  openstack/dds/v3/connection/ListConnections.go
  openstack/dds/v3/connection/ListSessions.go
  openstack/dds/v3/flavors/List.go
  openstack/dds/v3/flavors/requests.go
  openstack/dds/v3/flavors/results.go
  openstack/dds/v3/flavors/urls.go
  openstack/dds/v3/instances/AddNode.go
  openstack/dds/v3/instances/BindEIP.go
  openstack/dds/v3/instances/Create.go
  openstack/dds/v3/instances/Delete.go
  openstack/dds/v3/instances/EnableConfigIp.go
  openstack/dds/v3/instances/List.go
  openstack/dds/v3/instances/ManageSSL.go
  openstack/dds/v3/instances/ModifyInternalIp.go
  openstack/dds/v3/instances/ModifyPort.go
  openstack/dds/v3/instances/ModifySG.go
  openstack/dds/v3/instances/ModifySpec.go
  openstack/dds/v3/instances/Restart.go
  openstack/dds/v3/instances/ScaleStorage.go
  openstack/dds/v3/instances/Switchover.go
  openstack/dds/v3/instances/UnbindEIP.go
  openstack/dds/v3/instances/UpdateName.go
  openstack/dds/v3/instances/job.go
  openstack/dds/v3/instances/requests.go
  openstack/dds/v3/instances/results.go
  openstack/dds/v3/instances/urls.go
  openstack/dds/v3/job/Get.go
Labels: enhancement, gate

#488 [DDS]: Password reset & fix
  acceptance/openstack/dds/v3/instances_test.go
  openstack/dds/v3/instances/ChangePassword.go
  openstack/dds/v3/instances/Create.go
Labels: gate
