Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2022-07, with the labels that each got.

#364 CBR/Backups: additional query opt to get resource by ID
  acceptance/openstack/cbr/v3/backups_test.go
  acceptance/openstack/cbr/v3/helpers.go
  openstack/cbr/v3/backups/requests.go
  openstack/cbr/v3/backups/results.go
Labels: gate

#365 css version fix
  openstack/css/v1/clusters/requests.go
  openstack/css/v1/clusters/testing/fixtures.go
Labels: gate

#367 DMS/Topics: add topics functionality for DMS
  acceptance/openstack/dms/v1/instances_test.go
  openstack/dms/v1/topics/requests.go
  openstack/dms/v1/topics/results.go
  openstack/dms/v1/topics/urls.go
Labels: enhancement, gate

#369 [KMS] Canceling the Scheduled Deletion of a CMK
  acceptance/openstack/kms/v1/keys_test.go
  openstack/kms/v1/keys/requests.go
  openstack/kms/v1/keys/results.go
  openstack/kms/v1/keys/urls.go
Labels: enhancement, gate

#373 [IAM]: Custom policies support
  acceptance/clients/clients.go
  acceptance/openstack/identity/v3/policies_test.go
  openstack/identity/v3/policies/requests.go
  openstack/identity/v3/policies/results.go
  openstack/identity/v3/policies/urls.go
Labels: enhancement, gate

#371 [CBR] implements all the APIs of Tag.
  acceptance/openstack/cbr/v3/tags_test.go
  openstack/cbr/v3/tags/requests.go
  openstack/cbr/v3/tags/results.go
  openstack/cbr/v3/tags/urls.go
  openstack/cbr/v3/vaults/results.go
  provider_client.go
  results.go
Labels: enhancement, gate

#374 [CBR] Clean up redundant code.
  acceptance/openstack/cbr/v3/tags_test.go
  openstack/cbr/v3/tags/requests.go
  openstack/cbr/v3/tags/results.go
  openstack/cbr/v3/tags/urls.go
  openstack/cbr/v3/vaults/requests.go
  openstack/cbr/v3/vaults/results.go
  openstack/common/tags/requests.go
Labels: enhancement, gate

#376 [IAM]: update users module + tests
  acceptance/clients/clients.go
  acceptance/openstack/identity/v3/policies_test.go
  acceptance/openstack/identity/v3/users_test.go
  openstack/identity/v3/users/requests.go
Labels: gate

#377 [CSBS] `SpaceSavingRatio` type to float
  openstack/csbs/v1/backup/results.go
Labels: bug, gate

#380 [DCS] Change Capacity to float32
  acceptance/openstack/dcs/v1/helpers.go
  openstack/dcs/v1/instances/requests.go
  openstack/dcs/v1/instances/results.go
Labels: enhancement, gate

#386 [DCS]: Float value fix
  openstack/dcs/v1/instances/requests.go
  openstack/dcs/v1/instances/results.go
Labels: gate

#388 [DCS] Add CapacityMinor
  acceptance/openstack/dcs/v1/configs_test.go
  acceptance/openstack/dcs/v1/helpers.go
  openstack/dcs/v1/instances/results.go
Labels: enhancement, gate
