Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2022-09, with the labels that each got.

#413 Set smn topic to false in CTS test (probably bug)
  acceptance/openstack/cts/v1/helpers.go
  acceptance/openstack/cts/v1/trackers_test.go
Labels: bug, gate

#403 [Refactor] BMS
  openstack/bms/v2/flavors/doc.go
  openstack/bms/v2/flavors/list.go
  openstack/bms/v2/flavors/results.go
  openstack/bms/v2/flavors/urls.go
  openstack/bms/v2/keypairs/doc.go
  openstack/bms/v2/keypairs/list.go
  openstack/bms/v2/keypairs/results.go
  openstack/bms/v2/keypairs/testing/fixtures.go
  openstack/bms/v2/keypairs/testing/requests_test.go
  openstack/bms/v2/keypairs/urls.go
  openstack/bms/v2/nics/doc.go
  openstack/bms/v2/nics/get.go
  openstack/bms/v2/nics/list.go
  openstack/bms/v2/nics/results.go
  openstack/bms/v2/nics/testing/requests_test.go
  openstack/bms/v2/nics/urls.go
  openstack/bms/v2/servers/doc.go
  openstack/bms/v2/servers/get.go
  openstack/bms/v2/servers/list.go
  openstack/bms/v2/servers/results.go
  openstack/bms/v2/servers/testing/requests_test.go
  openstack/bms/v2/servers/urls.go
  openstack/bms/v2/tags/create.go
  openstack/bms/v2/tags/delete.go
  openstack/bms/v2/tags/doc.go
  openstack/bms/v2/tags/get.go
  openstack/bms/v2/tags/requests.go
  openstack/bms/v2/tags/results.go
  openstack/bms/v2/tags/testing/requests_test.go
  openstack/bms/v2/tags/urls.go
Labels: enhancement, gate

#407 [extract] Enhancement
  internal/extract/json.go
  pagination/single.go
  provider_client.go
Labels: enhancement, gate

#399 [LTS] fix groups create
  acceptance/clients/clients.go
  acceptance/openstack/lts/v2/loggroups_test.go
  openstack/lts/v2/loggroups/requests.go
  openstack/lts/v2/loggroups/results.go
Labels: enhancement, gate

#418 [BMS] Fix Extract body
  openstack/bms/v2/nics/results.go
  openstack/bms/v2/servers/results.go
Labels: bug, gate

#416 [Enhancement] Restrict internal response body types
  internal/extract/doc.go
  internal/extract/json.go
  internal/extract/json_test.go
  openstack/blockstorage/extensions/quotasets/testing/fixtures.go
  openstack/blockstorage/v1/snapshots/results.go
  openstack/blockstorage/v2/snapshots/results.go
  openstack/blockstorage/v3/snapshots/results.go
  openstack/bms/v2/flavors/results.go
  openstack/bms/v2/keypairs/results.go
  openstack/bms/v2/nics/results.go
  openstack/bms/v2/servers/results.go
  openstack/common/metadata/metadata.go
  openstack/compute/v2/extensions/quotasets/requests.go
  openstack/compute/v2/extensions/quotasets/testing/requests_test.go
  openstack/compute/v2/images/testing/requests_test.go
  openstack/compute/v2/servers/testing/results_test.go
  openstack/css/v1/clusters/results.go
  openstack/dns/v2/recordsets/testing/requests_test.go
  openstack/identity/v3/tokens/testing/fixtures.go
  openstack/imageservice/v2/imagedata/requests.go
  openstack/imageservice/v2/imagedata/results.go
  openstack/imageservice/v2/imagedata/testing/requests_test.go
  openstack/networking/v2/extensions/vpnaas/siteconnections/testing/requests_test.go
  openstack/networking/v2/subnets/testing/results_test.go
  openstack/objectstorage/v1/containers/results.go
  openstack/objectstorage/v1/objects/results.go
  openstack/rts/v1/stacktemplates/results.go
  openstack/waf/v1/certificates/results.go
  pagination/http.go
  pagination/linked.go
  pagination/marker.go
  pagination/offset.go
  pagination/pager.go
  pagination/single.go
  pagination/testing/marker_test.go
  provider_client.go
  results.go
  testing/results_test.go
Labels: enhancement, gate

#404 [Refactor] CBR
  acceptance/openstack/cbr/v3/backups_test.go
  acceptance/openstack/cbr/v3/helpers.go
  acceptance/openstack/cbr/v3/policies_test.go
  acceptance/openstack/cbr/v3/tags_test.go
  acceptance/openstack/cbr/v3/tasks_test.go
  acceptance/openstack/cbr/v3/vaults_test.go
  openstack/cbr/v3/backups/delete.go
  openstack/cbr/v3/backups/get.go
  openstack/cbr/v3/backups/list.go
  openstack/cbr/v3/backups/requests.go
  openstack/cbr/v3/backups/restore_backup.go
  openstack/cbr/v3/backups/results.go
  openstack/cbr/v3/backups/urls.go
  openstack/cbr/v3/checkpoint/get.go
  openstack/cbr/v3/checkpoint/requests.go
  openstack/cbr/v3/checkpoint/results.go
  openstack/cbr/v3/checkpoint/urls.go
  openstack/cbr/v3/policies/create.go
  openstack/cbr/v3/policies/delete.go
  openstack/cbr/v3/policies/get.go
  openstack/cbr/v3/policies/list.go
  openstack/cbr/v3/policies/requests.go
  openstack/cbr/v3/policies/results.go
  openstack/cbr/v3/policies/testing/fixtures.go
  openstack/cbr/v3/policies/testing/requests_test.go
  openstack/cbr/v3/policies/update.go
  openstack/cbr/v3/policies/urls.go
  openstack/cbr/v3/tags/results.go
  openstack/cbr/v3/tags/show_vault_resource_instances.go
  openstack/cbr/v3/tags/tag.go
  openstack/cbr/v3/tags/urls.go
  openstack/cbr/v3/tasks/get.go
  openstack/cbr/v3/tasks/list.go
  openstack/cbr/v3/tasks/requests.go
  openstack/cbr/v3/tasks/results.go
  openstack/cbr/v3/tasks/urls.go
  openstack/cbr/v3/vaults/associate_resources.go
  openstack/cbr/v3/vaults/bind_policy.go
  openstack/cbr/v3/vaults/create.go
  openstack/cbr/v3/vaults/delete.go
  openstack/cbr/v3/vaults/dissociate_resources.go
  openstack/cbr/v3/vaults/get.go
  openstack/cbr/v3/vaults/requests.go
  openstack/cbr/v3/vaults/results.go
  openstack/cbr/v3/vaults/unbind_policy.go
  openstack/cbr/v3/vaults/update.go
  openstack/cbr/v3/vaults/urls.go
Labels: enhancement, gate

#441 [DCS]: whitelist feature fix & test
  acceptance/openstack/dcs/v1/configs_test.go
  openstack/dcs/v2/whitelists/requests.go
  openstack/dcs/v2/whitelists/urls.go
Labels: enhancement, gate

#424 Move building opts to `internal/build` package / Add pointer converter
  internal/build/backward_test.go
  internal/build/doc.go
  internal/build/errs.go
  internal/build/headers.go
  internal/build/headers_test.go
  internal/build/query_string.go
  internal/build/query_string_test.go
  internal/build/request_body.go
  internal/build/request_body_test.go
  internal/build/tags.go
  internal/build/tags_test.go
  internal/multierr/multierr.go
  openstack/common/pointerto/doc.go
  openstack/common/pointerto/pointers.go
  openstack/common/pointerto/pointers_test.go
  params.go
Labels: enhancement, gate, post
