Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2023-07, with the labels that each got.

#541 [DRS]: precheck method implement
  acceptance/openstack/drs/v3/tasks_test.go
  openstack/drs/v3/public/PreCheckTask.go
Labels: gate, post

#542 [OBS]: Implement parallel fs for obs
  acceptance/openstack/obs/v1/obs_pfs_test.go
  acceptance/openstack/obs/v1/obs_test.go
  openstack/obs/const.go
  openstack/obs/convert.go
  openstack/obs/model_bucket.go
Labels: gate

#543 [FWAAS]: remove `omitempty` from souce/destination ports
  acceptance/openstack/networking/v2/fw_rule_test.go
  openstack/networking/v2/extensions/fwaas_v2/rules/requests.go
Labels: gate

#544 RDS: table names case sensitivity
  acceptance/openstack/rds/v3/helpers.go
  openstack/rds/v3/instances/Create.go
Labels: gate

#545 RDS: `RestoreToNew` lowercase table names
  acceptance/openstack/rds/v3/rds_test.go
  openstack/rds/v3/backups/RestoreToNew.go
Labels: gate

#551 IAM: implement OIDC support for provider resource
  acceptance/openstack/identity/v3/fed_providers_test.go
  openstack/identity/v3/federation/providers/CreateOIDC.go
  openstack/identity/v3/federation/providers/GetOIDC.go
  openstack/identity/v3/federation/providers/UpdateOIDC.go
Labels: gate

#550 [IAM] bring identity tests to actual state
  acceptance/openstack/identity/v3/domains_test.go
  acceptance/openstack/identity/v3/endpoint_test.go
  acceptance/openstack/identity/v3/fed_mappings_test.go
  acceptance/openstack/identity/v3/fed_providers_test.go
  acceptance/openstack/identity/v3/groups_test.go
  acceptance/openstack/identity/v3/projects_test.go
  acceptance/openstack/identity/v3/regions_test.go
  acceptance/openstack/identity/v3/roles_test.go
  acceptance/openstack/identity/v3/service_test.go
Labels: gate

#529 [WAF] Instances and hosts support for dedicated version
  acceptance/clients/clients.go
  acceptance/openstack/waf-premium/v1/helpers.go
  acceptance/openstack/waf-premium/v1/host_test.go
  acceptance/openstack/waf-premium/v1/instance_test.go
  openstack/client.go
  openstack/waf-premium/v1/hosts/Create.go
  openstack/waf-premium/v1/hosts/Delete.go
  openstack/waf-premium/v1/hosts/Get.go
  openstack/waf-premium/v1/hosts/List.go
  openstack/waf-premium/v1/hosts/Update.go
  openstack/waf-premium/v1/instances/Create.go
  openstack/waf-premium/v1/instances/Delete.go
  openstack/waf-premium/v1/instances/Get.go
  openstack/waf-premium/v1/instances/List.go
  openstack/waf-premium/v1/instances/Update.go
  openstack/waf-premium/v1/instances/Upgrade.go
Labels: enhancement, gate, post

#554 [WAFD] added `resourceSpecCode` response attribute
  acceptance/openstack/waf-premium/v1/instance_test.go
  openstack/waf-premium/v1/instances/Get.go
Labels: gate

#555 [WAF] dedicated certificate
  acceptance/openstack/waf-premium/v1/certificate_test.go
  acceptance/openstack/waf-premium/v1/helpers.go
  acceptance/openstack/waf-premium/v1/host_test.go
  acceptance/openstack/waf-premium/v1/instance_test.go
  openstack/waf-premium/v1/certificates/Create.go
  openstack/waf-premium/v1/certificates/Delete.go
  openstack/waf-premium/v1/certificates/Get.go
  openstack/waf-premium/v1/certificates/List.go
Labels: gate
