Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2023-06, with the labels that each got.

#534 [CES]: alarm frequency & alarm type implementation
  acceptance/openstack/ces/v1/alarms_test.go
  openstack/ces/v1/alarms/create_alarm.go
  openstack/ces/v1/alarms/results.go
Labels: gate

#535 [WAF]: alarm page implementation
  acceptance/openstack/waf/v1/domains_test.go
  openstack/waf/v1/domains/requests.go
  openstack/waf/v1/domains/results.go
Labels: gate

#536 [CTS]: tracker v3 implementation for SWISS
  acceptance/openstack/cts/helpers.go
  acceptance/openstack/cts/v3/keyevents_test.go
  acceptance/openstack/cts/v3/trackers_test.go
  openstack/cts/v3/tracker/Create.go
  openstack/cts/v3/tracker/Delete.go
  openstack/cts/v3/tracker/List.go
  openstack/cts/v3/tracker/Update.go
  openstack/cts/v3/tracker/results.go
Labels: enhancement, gate

#458 [NEW] DIS
  acceptance/clients/clients.go
  acceptance/openstack/dis/v2/dis_test.go
  openstack/client.go
  openstack/dis/v2/apps/CreateApp.go
  openstack/dis/v2/apps/DeleteApp.go
  openstack/dis/v2/apps/GetApp.go
  openstack/dis/v2/apps/GetAppStatus.go
  openstack/dis/v2/apps/ListApp.go
  openstack/dis/v2/checkpoints/CommitCheckpoint.go
  openstack/dis/v2/checkpoints/DeleteCheckpoint.go
  openstack/dis/v2/checkpoints/GetCheckpoint.go
  openstack/dis/v2/data/GetCursor.go
  openstack/dis/v2/data/GetRecords.go
  openstack/dis/v2/data/PutRecords.go
  openstack/dis/v2/dump/CreateCloudTableDumpTask.go
  openstack/dis/v2/dump/CreateDLIDumpTask.go
  openstack/dis/v2/dump/CreateDWSDumpTask.go
  openstack/dis/v2/dump/CreateMRSDumpTask.go
  openstack/dis/v2/dump/CreateOBSDumpTask.go
  openstack/dis/v2/dump/DeleteTransferTask.go
  openstack/dis/v2/dump/GetTransferTask.go
  openstack/dis/v2/dump/ListTransferTasks.go
  openstack/dis/v2/dump/TransferTaskAction.go
  openstack/dis/v2/monitors/GetPartitionMonitor.go
  openstack/dis/v2/monitors/GetStreamMonitor.go
  openstack/dis/v2/streams/CreatePolicyRule.go
  openstack/dis/v2/streams/CreateStream.go
  openstack/dis/v2/streams/DeleteStream.go
  openstack/dis/v2/streams/GetPolicyRule.go
  openstack/dis/v2/streams/GetStream.go
  openstack/dis/v2/streams/ListStreams.go
  openstack/dis/v2/streams/UpdatePartitionCount.go
  openstack/dis/v2/streams/UpdateStream.go
  params.go
Labels: enhancement, gate, need acceptance, post

#539 [DIS] missed type fixes
  openstack/dis/v2/data/GetRecords.go
  openstack/dis/v2/dump/GetTransferTask.go
  openstack/dis/v2/dump/ListTransferTasks.go
  openstack/dis/v2/streams/CreateStream.go
  openstack/dis/v2/streams/GetStream.go
  openstack/dis/v2/streams/ListStreams.go
  openstack/dis/v2/streams/UpdateStream.go
Labels: gate

#454 [NEW] DRS
  acceptance/clients/clients.go
  acceptance/openstack/drs/v3/tasks_test.go
  acceptance/openstack/rds/v3/configurations_test.go
  acceptance/openstack/rds/v3/helpers.go
  acceptance/openstack/rds/v3/rds_test.go
  openstack/client.go
  openstack/drs/v3/public/BatchCreateTasks.go
  openstack/drs/v3/public/BatchDeleteTasks.go
  openstack/drs/v3/public/BatchListTaskDetails.go
  openstack/drs/v3/public/BatchListTaskStatus.go
  openstack/drs/v3/public/BatchModifyTask.go
  openstack/drs/v3/public/BatchSetSpeed.go
  openstack/drs/v3/public/BatchStartTasks.go
  openstack/drs/v3/public/BatchTestConnections.go
  openstack/utils/utils.go
Labels: enhancement, gate
