Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2023-08, with the labels that each got.

#558 [WAF] dedicated policies
  acceptance/openstack/obs/v1/obs_test.go
  acceptance/openstack/rds/v3/helpers.go
  acceptance/openstack/waf-premium/v1/policy_test.go
  openstack/waf-premium/v1/policies/Create.go
  openstack/waf-premium/v1/policies/Delete.go
  openstack/waf-premium/v1/policies/Get.go
  openstack/waf-premium/v1/policies/List.go
  openstack/waf-premium/v1/policies/Update.go
Labels: gate, post

#559 [OBS] added bucket lifecycle policy test
  acceptance/openstack/obs/v1/obs_test.go
Labels: gate

#560 OBS: Cross-region replication
  acceptance/openstack/obs/v1/obs_test.go
  openstack/obs/client_bucket.go
  openstack/obs/const.go
  openstack/obs/convert.go
  openstack/obs/model_base.go
  openstack/obs/model_bucket.go
  openstack/obs/trait.go
Labels: gate

#562 RDS: Add `ssl_enable` parameter for LIST struct
  acceptance/openstack/rds/v3/rds_test.go
  openstack/rds/v3/instances/List.go
Labels: gate

#563 IAM: New user API
  acceptance/clients/clients.go
  acceptance/openstack/identity/v3.0/users_test.go
  openstack/identity/v3.0/users/CreateUser.go
  openstack/identity/v3.0/users/GetUser.go
  openstack/identity/v3.0/users/ModifyUser.go
Labels: gate

#564 IAM: UpdateOpts fix for users
  acceptance/openstack/identity/v3.0/users_test.go
  openstack/identity/v3.0/users/ModifyUser.go
Labels: gate

#565 CCE: Custom deletion implementation
  acceptance/openstack/cce/helpers.go
  openstack/cce/v3/clusters/requests.go
Labels: gate

#566 RDS: Fix backup `keepdays` bug with 0 value
  acceptance/openstack/rds/v3/rds_test.go
  openstack/rds/v3/backups/Update.go
Labels: gate

#546 [DCaaS] Implementing Direct Connect as a Service
  .gitignore
  acceptance/clients/clients.go
  acceptance/openstack/dcaas/v2/dcaas_acc_test.go
  acceptance/openstack/dcaas/v2/direct_connect_endpoint_group_test.go
  acceptance/openstack/dcaas/v2/direct_connect_test.go
  acceptance/openstack/dcaas/v2/virtual_gateway_test.go
  acceptance/openstack/dcaas/v2/virtual_interface_test.go
  openstack/client.go
  openstack/dcaas/v2/dc-endpoint-group/Create.go
  openstack/dcaas/v2/dc-endpoint-group/Delete.go
  openstack/dcaas/v2/dc-endpoint-group/Get.go
  openstack/dcaas/v2/dc-endpoint-group/List.go
  openstack/dcaas/v2/dc-endpoint-group/Update.go
  openstack/dcaas/v2/direct-connect/Create.go
  openstack/dcaas/v2/direct-connect/Delete.go
  openstack/dcaas/v2/direct-connect/Get.go
  openstack/dcaas/v2/direct-connect/List.go
  openstack/dcaas/v2/direct-connect/Update.go
  openstack/dcaas/v2/virtual-gateway/Create.go
  openstack/dcaas/v2/virtual-gateway/Delete.go
  openstack/dcaas/v2/virtual-gateway/Get.go
  openstack/dcaas/v2/virtual-gateway/List.go
  openstack/dcaas/v2/virtual-gateway/Update.go
  openstack/dcaas/v2/virtual-interface/Create.go
  openstack/dcaas/v2/virtual-interface/Delete.go
  openstack/dcaas/v2/virtual-interface/Get.go
  openstack/dcaas/v2/virtual-interface/List.go
  openstack/dcaas/v2/virtual-interface/Update.go
Labels: enhancement, gate

#567 [WAF] dedicated rules
  acceptance/openstack/waf-premium/v1/rule_test.go
  openstack/waf-premium/v1/rules/ChangeRuleStatus.go
  openstack/waf-premium/v1/rules/CreateAntiCrawler.go
  openstack/waf-premium/v1/rules/CreateAntiLeakage.go
  openstack/waf-premium/v1/rules/CreateAntiTamper.go
  openstack/waf-premium/v1/rules/CreateBlacklist.go
  openstack/waf-premium/v1/rules/CreateCc.go
  openstack/waf-premium/v1/rules/CreateCustom.go
  openstack/waf-premium/v1/rules/CreateGeoIp.go
  openstack/waf-premium/v1/rules/CreateIgnore.go
  openstack/waf-premium/v1/rules/CreateKnownAttackSource.go
  openstack/waf-premium/v1/rules/CreatePrivacy.go
  openstack/waf-premium/v1/rules/CreateReferenceTable.go
  openstack/waf-premium/v1/rules/Delete.go
  openstack/waf-premium/v1/rules/GetAntiCrawler.go
  openstack/waf-premium/v1/rules/GetAntiLeakage.go
  openstack/waf-premium/v1/rules/GetAntiTamper.go
  openstack/waf-premium/v1/rules/GetBlacklist.go
  openstack/waf-premium/v1/rules/GetCc.go
  openstack/waf-premium/v1/rules/GetCustom.go
  openstack/waf-premium/v1/rules/GetGeoIp.go
  openstack/waf-premium/v1/rules/GetIgnore.go
  openstack/waf-premium/v1/rules/GetKnowAttackSource.go
  openstack/waf-premium/v1/rules/GetPrivacy.go
  openstack/waf-premium/v1/rules/GetReferenceTable.go
  openstack/waf-premium/v1/rules/ListAntiCrawler.go
  openstack/waf-premium/v1/rules/ListAntiLeakage.go
  openstack/waf-premium/v1/rules/ListAntiTamper.go
  openstack/waf-premium/v1/rules/ListBlacklist.go
  openstack/waf-premium/v1/rules/ListCc.go
  openstack/waf-premium/v1/rules/ListCustom.go
  openstack/waf-premium/v1/rules/ListGeoIp.go
  openstack/waf-premium/v1/rules/ListIgnore.go
  openstack/waf-premium/v1/rules/ListKnownAttackSource.go
  openstack/waf-premium/v1/rules/ListPrivacy.go
  openstack/waf-premium/v1/rules/ListReferenceTable.go
  openstack/waf-premium/v1/rules/UpdateAntiCrawler.go
  openstack/waf-premium/v1/rules/UpdateAntiLeakage.go
  openstack/waf-premium/v1/rules/UpdateAntiTamper.go
  openstack/waf-premium/v1/rules/UpdateBlacklist.go
  openstack/waf-premium/v1/rules/UpdateCc.go
  openstack/waf-premium/v1/rules/UpdateCustom.go
  openstack/waf-premium/v1/rules/UpdateGeoIp.go
  openstack/waf-premium/v1/rules/UpdateIgnore.go
  openstack/waf-premium/v1/rules/UpdateKnownAttackSource.go
  openstack/waf-premium/v1/rules/UpdatePrivacy.go
  openstack/waf-premium/v1/rules/UpdateReferenceTable.go
Labels: gate

#569 [ELB] ipgroup update fix
  acceptance/openstack/elb/v3/ipgroups_test.go
  openstack/elb/v3/listeners/requests.go
Labels: bug, gate

#570 [ELB] ipgroup IpList can be empty now
  acceptance/openstack/elb/v3/ipgroups_test.go
  openstack/elb/v3/ipgroups/Create.go
  openstack/elb/v3/ipgroups/Update.go
Labels: gate

#571 [TMS]: predefined tags
  acceptance/clients/clients.go
  acceptance/openstack/tms/tags_test.go
  openstack/client.go
Labels: gate
