Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2023-09, with the labels that each got.

#574 [IAM]: Temporary AK/SK duration fix
  acceptance/openstack/identity/v3/agency_test.go
  openstack/identity/v3/credentials/requests.go
Labels: gate

#576 [DRS]: Precheck results method
  openstack/drs/v3/public/BatchCheckResults.go
Labels: gate

#578 [CLIENT] move BackOff retry parameters to provider client level
  acceptance/openstack/client_test.go
  acceptance/openstack/networking/v2/sgs/sg_test.go
  provider_client.go
Labels: enhancement, gate

#580 [WAF] dedicated rules attributes update
  acceptance/openstack/ces/v1/events_test.go
  acceptance/openstack/waf-premium/v1/rule_test.go
  openstack/waf-premium/v1/rules/CreateAntiLeakage.go
  openstack/waf-premium/v1/rules/CreateAntiTamper.go
  openstack/waf-premium/v1/rules/CreateBlacklist.go
  openstack/waf-premium/v1/rules/CreateCc.go
  openstack/waf-premium/v1/rules/CreateCustom.go
  openstack/waf-premium/v1/rules/CreateGeoIp.go
  openstack/waf-premium/v1/rules/CreateIgnore.go
  openstack/waf-premium/v1/rules/CreatePrivacy.go
  openstack/waf-premium/v1/rules/UpdateBlacklist.go
Labels: bug, gate, post

#452 [NEW] GaussDB for MySQL
  acceptance/clients/clients.go
  acceptance/openstack/gaussdb/v3/db_test.go
  openstack/client.go
  openstack/gaussdb/v3/ListConfigurations.go
  openstack/gaussdb/v3/ShowEngineVersion.go
  openstack/gaussdb/v3/ShowFlavors.go
  openstack/gaussdb/v3/ShowJobInfo.go
  openstack/gaussdb/v3/backup/CreateBackup.go
  openstack/gaussdb/v3/backup/GetPolicy.go
  openstack/gaussdb/v3/backup/ListBackups.go
  openstack/gaussdb/v3/backup/UpdatePolicy.go
  openstack/gaussdb/v3/instance/ChangeSpec.go
  openstack/gaussdb/v3/instance/CreateInstance.go
  openstack/gaussdb/v3/instance/CreateReadonlyNode.go
  openstack/gaussdb/v3/instance/DeleteInstance.go
  openstack/gaussdb/v3/instance/DeleteReadonlyNode.go
  openstack/gaussdb/v3/instance/GetInstance.go
  openstack/gaussdb/v3/instance/ListInstances.go
  openstack/gaussdb/v3/instance/ResetPassword.go
  openstack/gaussdb/v3/instance/UpdateName.go
  openstack/gaussdb/v3/util.go
  params.go
Labels: enhancement, gate

#581 [SFST]: Enhanced versions
  openstack/sfs_turbo/v1/shares/requests.go
Labels: gate

#582 [GAUSSDB]: Fix backup_strategy update
  openstack/gaussdb/v3/backup/UpdatePolicy.go
Labels: gate
