Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2024-07, with the labels that each got.

#691 DCS: cert download method
  acceptance/openstack/dcs/v2/ssl_test.go
  openstack/dcs/v2/ssl/DownloadCert.go
Labels: gate

#692 IAM: swiss users admin update
  acceptance/openstack/identity/v3.0/users_test.go
  openstack/identity/v3.0/users/ModifyUserAdmin.go
Labels: gate

#693 [ER]: vpc attachments
  acceptance/openstack/er/vpc_attachments_test.go
  openstack/er/v3/vpc/Create.go
  openstack/er/v3/vpc/Delete.go
  openstack/er/v3/vpc/Get.go
  openstack/er/v3/vpc/List.go
  openstack/er/v3/vpc/Update.go
Labels: gate

#694 [ER]: vpc update description change
  acceptance/openstack/er/vpc_attachments_test.go
  openstack/er/v3/vpc/Update.go
Labels: gate

#695 [HSS] server group
  acceptance/clients/clients.go
  acceptance/openstack/apigw/v2/channel_test.go
  acceptance/openstack/common.go
  acceptance/openstack/hss/v5/server_group_test.go
  openstack/client.go
  openstack/hss/v5/host/ChangeProtectionStatus.go
  openstack/hss/v5/host/Create.go
  openstack/hss/v5/host/Delete.go
  openstack/hss/v5/host/List.go
  openstack/hss/v5/host/ListHost.go
  openstack/hss/v5/host/Update.go
Labels: enhancement, gate

#696 [WAF] fix AdvancedIgnoreObject type
  acceptance/openstack/waf-premium/v1/rule_test.go
  openstack/waf-premium/v1/rules/CreateIgnore.go
Labels: bug, documentation, gate

#697 [ER]: route tables
  acceptance/openstack/er/route_tables_test.go
  acceptance/openstack/er/router_test.go
  acceptance/openstack/er/vpc_attachments_test.go
  openstack/er/v3/route_table/Create.go
  openstack/er/v3/route_table/Delete.go
  openstack/er/v3/route_table/Get.go
  openstack/er/v3/route_table/List.go
  openstack/er/v3/route_table/Update.go
  openstack/er/v3/vpc/List.go
Labels: gate

#700 [WAFD] ignore rule AdvancedIgnoreObject.Contents fix
  acceptance/openstack/waf-premium/v1/rule_test.go
  openstack/waf-premium/v1/rules/CreateIgnore.go
Labels: gate

#701 [WAFD] Policy Extend params support
  acceptance/openstack/waf-premium/v1/policy_test.go
  openstack/waf-premium/v1/policies/Update.go
Labels: enhancement, gate

#702 ER: association/propagation
  acceptance/openstack/er/associations_test.go
  acceptance/openstack/er/propagations_test.go
  openstack/er/v3/association/Create.go
  openstack/er/v3/association/Delete.go
  openstack/er/v3/association/List.go
  openstack/er/v3/propagation/Create.go
  openstack/er/v3/propagation/Delete.go
  openstack/er/v3/propagation/List.go
Labels: gate

#703 ER: routes
  acceptance/openstack/er/routes_test.go
  openstack/er/v3/route/Create.go
  openstack/er/v3/route/Delete.go
  openstack/er/v3/route/Get.go
  openstack/er/v3/route/List.go
  openstack/er/v3/route/ListStatic.go
  openstack/er/v3/route/Update.go
Labels: gate
