Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2024-09, with the labels that each got.

#715 [Test/fix] Fix RDS acceptance test/Update postgresql version
  acceptance/openstack/rds/v3/flavors_test.go
Labels: gate

#718 [Refactor] Refactor SDRS protections group
  acceptance/openstack/sdrs/v1/helpers.go
  openstack/sdrs/v1/protectiongroups/Create.go
  openstack/sdrs/v1/protectiongroups/Delete.go
  openstack/sdrs/v1/protectiongroups/Disable.go
  openstack/sdrs/v1/protectiongroups/Enable.go
  openstack/sdrs/v1/protectiongroups/Get.go
  openstack/sdrs/v1/protectiongroups/Update.go
  openstack/sdrs/v1/protectiongroups/requests.go
  openstack/sdrs/v1/protectiongroups/results.go
  openstack/sdrs/v1/protectiongroups/results_job.go
  openstack/sdrs/v1/protectiongroups/urls.go
Labels: gate

#722 [Fix.] Enabling and Disabling of ProtectionGroup for SDRS
  acceptance/openstack/common.go
  acceptance/openstack/sdrs/v1/helpers.go
  acceptance/openstack/sdrs/v1/protectedinstances_test.go
  openstack/sdrs/v1/protectiongroups/Disable.go
  openstack/sdrs/v1/protectiongroups/Enable.go
  openstack/sdrs/v1/protectiongroups/results_job.go
Labels: bug, gate

#721 [Fix.] IsAutoRenew and IsAutoPay type changed to string
  acceptance/openstack/cce/v3/nodepool_test.go
  openstack/cce/v3/nodepools/requests.go
  openstack/cce/v3/nodes/results.go
  openstack/compute/v2/extensions/keypairs/requests.go
Labels: bug, gate

#725 [Feat.] Enterprise VPN Gateway
  acceptance/clients/clients.go
  acceptance/openstack/evpn/gateway_test.go
  openstack/client.go
  openstack/evpn/v5/gateway/Create.go
  openstack/evpn/v5/gateway/Delete.go
  openstack/evpn/v5/gateway/Get.go
  openstack/evpn/v5/gateway/List.go
  openstack/evpn/v5/gateway/ListAZs.go
  openstack/evpn/v5/gateway/Update.go
Labels: enhancement, gate

#726 DMS: product v2 fix ist
  openstack/dms/v2/products/List.go
Labels: gate
