Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2024-06, with the labels that each got.

#675 [OBS]: implement bucket inventories
  acceptance/openstack/obs/v1/obs_test.go
  openstack/obs/client_bucket.go
  openstack/obs/const.go
  openstack/obs/convert.go
  openstack/obs/model_base.go
  openstack/obs/model_bucket.go
  openstack/obs/trait.go
Labels: gate

#676 check gate label
  .github/workflows/label-gate.yaml
  .github/workflows/label-post.yaml
  .github/workflows/otc-golangci-lint.yaml
Labels: gate, post

#677 refactoring
  .github/workflows/label-gate.yaml
  .github/workflows/labels.yaml
  .github/workflows/otc-golangci-lint.yaml
Labels: gate, post

#678 refactoring
  .github/workflows/labels.yaml
Labels: gate, post

#680 CCE: master volume encryption feature
  acceptance/openstack/cce/helpers.go
  openstack/cce/v3/clusters/results.go
Labels: gate

#681 branch protection check
  .zuul.yaml
  .zuul.yaml.backup
Labels: gate

#682 Actions branch protection change
  .github/workflows/labels.yaml
  .zuul.yaml.backup
Labels: gate

#684 multiline fix
  .github/workflows/labels.yaml
Labels: gate

#683 skip actions now - need to prepare proper merge job befor
  .github/workflows/labels.yaml
  .zuul.yaml
Labels: gate

#685 ER: enterprise router
  acceptance/clients/clients.go
  acceptance/openstack/er/helpers.go
  acceptance/openstack/er/router_test.go
  openstack/client.go
  openstack/er/v3/instance/Create.go
  openstack/er/v3/instance/Delete.go
  openstack/er/v3/instance/Get.go
  openstack/er/v3/instance/List.go
  openstack/er/v3/instance/Update.go
Labels: gate

#686 CCE: Update nodepool parameters
  acceptance/openstack/cce/v3/nodepool_test.go
  openstack/cce/v3/nodes/results.go
Labels: gate

#687 compute ecs api update
  .github/workflows/labels.yaml
  acceptance/clients/clients.go
  acceptance/openstack/compute/v2/servers_test.go
  openstack/compute/v2/servers/requests.go
  openstack/compute/v2/servers/results.go
  openstack/compute/v2/servers/testing/fixtures.go
Labels: enhancement, gate

#689 Refactor ci.yaml and automerge.yaml for GH
  .github/workflows/automerge.yaml
  .github/workflows/ci.yaml
  .github/workflows/labels.yaml
  .github/workflows/otc-golangci-lint.yaml
  .old_zuul.yaml
Labels: gate
