Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2024-01, with the labels that each got.

#600 [VPC] Networking v1 subnet ipv6 support
  acceptance/openstack/networking/v1/subnet_test.go
  openstack/networking/v1/subnets/requests.go
  openstack/networking/v1/subnets/results.go
Labels: enhancement, gate

#601 [APIGW]: gateway
  acceptance/clients/clients.go
  acceptance/openstack/apigw/v2/gateway_test.go
  openstack/apigw/v2/gateway/Create.go
  openstack/apigw/v2/gateway/Delete.go
  openstack/apigw/v2/gateway/DisableEIP.go
  openstack/apigw/v2/gateway/EnableEIP.go
  openstack/apigw/v2/gateway/Get.go
  openstack/apigw/v2/gateway/List.go
  openstack/apigw/v2/gateway/QueryProgress.go
  openstack/apigw/v2/gateway/Update.go
  openstack/apigw/v2/gateway/UpdateEIP.go
  openstack/client.go
Labels: gate

#602 [DCAAS] list and get methods fixes
  acceptance/openstack/ces/v1/events_test.go
  acceptance/openstack/dcaas/v2/direct_connect_endpoint_group_test.go
  acceptance/openstack/dcaas/v2/virtual_gateway_test.go
  acceptance/openstack/dcaas/v2/virtual_interface_test.go
  openstack/dcaas/v2/virtual-gateway/Create.go
  openstack/dcaas/v2/virtual-gateway/List.go
  openstack/dcaas/v2/virtual-interface/Get.go
  openstack/dcaas/v2/virtual-interface/List.go
Labels: bug, gate

#603 [APIGW]: Env implementation
  acceptance/openstack/apigw/v2/env_test.go
  openstack/apigw/v2/env/Create.go
  openstack/apigw/v2/env/Delete.go
  openstack/apigw/v2/env/List.go
  openstack/apigw/v2/env/Update.go
Labels: enhancement, gate

#606 [DCAAS] virtual interface update fix
  acceptance/openstack/dcaas/v2/virtual_interface_test.go
  openstack/dcaas/v2/virtual-interface/Update.go
Labels: bug, gate

#604 [APIGW]: Group implementation
  acceptance/openstack/apigw/v2/group_test.go
  openstack/apigw/v2/group/Create.go
  openstack/apigw/v2/group/Delete.go
  openstack/apigw/v2/group/Get.go
  openstack/apigw/v2/group/List.go
  openstack/apigw/v2/group/Update.go
Labels: enhancement, gate

#605 [APIGW]: Env vars implementation
  acceptance/openstack/apigw/v2/env_vars_test.go
  openstack/apigw/v2/env_vars/Create.go
  openstack/apigw/v2/env_vars/Delete.go
  openstack/apigw/v2/env_vars/Get.go
  openstack/apigw/v2/env_vars/List.go
Labels: enhancement, gate

#607 [APIGW]: throttling policy management
  acceptance/openstack/apigw/v2/throttling_policy_test.go
  openstack/apigw/v2/tr_policy/Create.go
  openstack/apigw/v2/tr_policy/Delete.go
  openstack/apigw/v2/tr_policy/Get.go
  openstack/apigw/v2/tr_policy/List.go
  openstack/apigw/v2/tr_policy/Update.go
Labels: enhancement, gate

#608 RDS: auto-scaling APIs implementation
  acceptance/openstack/rds/v3/helpers.go
  acceptance/openstack/rds/v3/rds_test.go
  openstack/rds/v3/instances/GetAutoScaling.go
  openstack/rds/v3/instances/ManageAutoScaling.go
Labels: gate

#609 [APIGW]: api implementation
  acceptance/openstack/apigw/v2/api_test.go
  acceptance/openstack/apigw/v2/env_test.go
  acceptance/openstack/apigw/v2/group_test.go
  openstack/apigw/v2/api/Create.go
  openstack/apigw/v2/api/Delete.go
  openstack/apigw/v2/api/Get.go
  openstack/apigw/v2/api/List.go
  openstack/apigw/v2/api/ManageApi.go
  openstack/apigw/v2/api/Update.go
Labels: gate

#610 [VPC] update for ipv6 support
  acceptance/openstack/networking/v2/fw_rule_test.go
  acceptance/openstack/networking/v2/sgs/sg_test.go
  openstack/networking/v1/subnets/results.go
  openstack/networking/v2/extensions/security/rules/requests.go
Labels: enhancement, gate

#612 [SWR] fix offset type in ListTagsOpts to pass 0 value to request
  acceptance/openstack/swr/v2/repositories_test.go
  openstack/swr/v2/repositories/ListTags.go
Labels: bug, gate

#613 [APIGW]: signature management
  acceptance/openstack/apigw/v2/api_test.go
  acceptance/openstack/apigw/v2/signature_key_test.go
  openstack/apigw/v2/key/BindKey.go
  openstack/apigw/v2/key/Create.go
  openstack/apigw/v2/key/Delete.go
  openstack/apigw/v2/key/List.go
  openstack/apigw/v2/key/ListAPIBoundKeys.go
  openstack/apigw/v2/key/ListAPIUnboundKeys.go
  openstack/apigw/v2/key/ListBoundKeys.go
  openstack/apigw/v2/key/UnbindKey.go
  openstack/apigw/v2/key/Update.go
Labels: gate

#614 [WAF] fix cannot unmarshal error of bigint
  acceptance/openstack/waf/v1/certificates_test.go
  openstack/waf/v1/certificates/results.go
Labels: bug, gate

#616 [IAM] security endpoints
  acceptance/openstack/identity/v3.0/users_test.go
  acceptance/openstack/identity/v3/mfa_test.go
  openstack/identity/v3.0/security/GetLoginAuthPolicy.go
  openstack/identity/v3.0/security/GetLoginProtectionConfiguration.go
  openstack/identity/v3.0/security/GetOperationProtectionPolicy.go
  openstack/identity/v3.0/security/GetPasswordPolicy.go
  openstack/identity/v3.0/security/GetUserMfaDevice.go
  openstack/identity/v3.0/security/ListLoginProtectionConfiguration.go
  openstack/identity/v3.0/security/ListUserMfaDevices.go
  openstack/identity/v3.0/security/UpdateLoginAuthPolicy.go
  openstack/identity/v3.0/security/UpdateLoginProtectionConfiguration.go
  openstack/identity/v3.0/security/UpdateOperationProtectionPolicy.go
  openstack/identity/v3.0/security/UpdatePasswordPolicy.go
Labels: enhancement, gate

#617 [APIGW]: Throttling policies bind management
  acceptance/openstack/apigw/v2/throttling_policy_test.go
  openstack/apigw/v2/tr_policy/BindPolicy.go
  openstack/apigw/v2/tr_policy/ListAPIBoundPolicy.go
  openstack/apigw/v2/tr_policy/ListAPIUnboundPolicy.go
  openstack/apigw/v2/tr_policy/ListBoundPolicies.go
  openstack/apigw/v2/tr_policy/UnbindPolicy.go
Labels: gate

#618 [APIGW]: app implementation
  acceptance/openstack/apigw/v2/app_test.go
  openstack/apigw/v2/app/Create.go
  openstack/apigw/v2/app/Delete.go
  openstack/apigw/v2/app/Get.go
  openstack/apigw/v2/app/List.go
  openstack/apigw/v2/app/ResetSecret.go
  openstack/apigw/v2/app/Update.go
  openstack/apigw/v2/app/VerifyApp.go
Labels: gate

#619 [APIGW]: App code
  acceptance/openstack/apigw/v2/app_code_test.go
  openstack/apigw/v2/app_code/Create.go
  openstack/apigw/v2/app_code/Delete.go
  openstack/apigw/v2/app_code/GenerateAppCode.go
  openstack/apigw/v2/app_code/Get.go
  openstack/apigw/v2/app_code/List.go
Labels: gate

#620 [APIGW]: Throttling special policies
  acceptance/openstack/apigw/v2/special_throttle_test.go
  openstack/apigw/v2/tr_specials/Create.go
  openstack/apigw/v2/tr_specials/Delete.go
  openstack/apigw/v2/tr_specials/List.go
  openstack/apigw/v2/tr_specials/Update.go
Labels: gate

#621 [IAM] password policy type fix according docs
  openstack/identity/v3.0/security/UpdatePasswordPolicy.go
Labels: gate

#622 [APIGW]: App auth
  acceptance/openstack/apigw/v2/app_auth_test.go
  openstack/apigw/v2/app_auth/CancelAuth.go
  openstack/apigw/v2/app_auth/CreateAuth.go
  openstack/apigw/v2/app_auth/GetBoundApis.go
  openstack/apigw/v2/app_auth/GetBoundApps.go
  openstack/apigw/v2/app_auth/GetUnboundApis.go
Labels: gate

#623 [NATGW] dnat rule refactoring
  acceptance/openstack/networking/v2/extensions/dnatrulest_test.go
  openstack/networking/v2/extensions/dnatrules/Create.go
  openstack/networking/v2/extensions/dnatrules/Delete.go
  openstack/networking/v2/extensions/dnatrules/Get.go
  openstack/networking/v2/extensions/dnatrules/List.go
  openstack/networking/v2/extensions/dnatrules/requests.go
  openstack/networking/v2/extensions/dnatrules/results.go
  openstack/networking/v2/extensions/dnatrules/urls.go
Labels: enhancement, gate

#624 OBS: bucket object lock
  acceptance/openstack/obs/v1/obs_test.go
  openstack/obs/client_bucket.go
  openstack/obs/const.go
  openstack/obs/convert.go
  openstack/obs/model_base.go
  openstack/obs/model_bucket.go
  openstack/obs/trait.go
Labels: gate

#625 OBS: Cross-region data deletion
  acceptance/clients/clients.go
  acceptance/openstack/client_test.go
  acceptance/openstack/obs/v1/obs_test.go
  openstack/client.go
  openstack/objectstorage/v1/swauth/doc.go
  openstack/objectstorage/v1/swauth/requests.go
  openstack/obs/convert.go
  openstack/obs/model_base.go
Labels: gate
