Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2024-05, with the labels that each got.

#654 Implementation of DataArts Migrations links API
  acceptance/openstack/dataarts/v1.1/clusters_test.go
  acceptance/openstack/dataarts/v1.1/helpers.go
  acceptance/openstack/dataarts/v1.1/links_test.go
  openstack/dataarts/v1.1/link/Create.go
  openstack/dataarts/v1.1/link/Delete.go
  openstack/dataarts/v1.1/link/Get.go
  openstack/dataarts/v1.1/link/Update.go
  openstack/dataarts/v1.1/link/common.go
Labels: gate, post

#657 [FGS]: trigger fixes
  acceptance/openstack/fgs/v2/trigger_test.go
  openstack/fgs/v2/trigger/Create.go
  openstack/fgs/v2/trigger/Update.go
Labels: gate

#658 [FGS]: Events test
  acceptance/openstack/fgs/v2/events_test.go
  openstack/fgs/v2/events/Create.go
  openstack/fgs/v2/events/Delete.go
  openstack/fgs/v2/events/Get.go
  openstack/fgs/v2/events/List.go
  openstack/fgs/v2/events/Update.go
Labels: gate

#659 css api was updated
  acceptance/openstack/css/v1/snapshots_test.go
  openstack/css/v1/clusters/results.go
  openstack/css/v1/snapshots/UpdateConfiguration.go
Labels: enhancement, gate, dependencies

#661 [CTS]: v3 API update
  acceptance/openstack/cts/v3/trackers_test.go
  openstack/cts/v3/tracker/Create.go
  openstack/cts/v3/tracker/List.go
  openstack/cts/v3/tracker/Update.go
  openstack/cts/v3/tracker/results.go
Labels: gate

#663 [APIGW] list app codes of app
  acceptance/openstack/apigw/v2/app_code_test.go
  openstack/apigw/v2/app_code/ListAppsCodes.go
Labels: gate

#664 [DCAAS]: gateway ipv6 support
  acceptance/openstack/dcaas/v2/virtual_gateway_test.go
  openstack/dcaas/v2/virtual-gateway/Create.go
Labels: gate

#665 [DCAAS]: update ipv6
  openstack/dcaas/v2/virtual-gateway/Update.go
Labels: gate

#655 Implementation of DataArts job API
  acceptance/openstack/dataarts/v1.1/links_test.go
  openstack/dataarts/v1.1/job/CreateRandom.go
  openstack/dataarts/v1.1/job/CreateSpecific.go
  openstack/dataarts/v1.1/job/Delete.go
  openstack/dataarts/v1.1/job/Get.go
  openstack/dataarts/v1.1/job/GetHistory.go
  openstack/dataarts/v1.1/job/GetStatus.go
  openstack/dataarts/v1.1/job/Start.go
  openstack/dataarts/v1.1/job/Stop.go
  openstack/dataarts/v1.1/job/Update.go
  openstack/dataarts/v1.1/job/common.go
Labels: gate

#656 Implementation of DataArts Factory scripts API
  acceptance/clients/clients.go
  acceptance/openstack/dataarts/v1.1/clusters_test.go
  acceptance/openstack/dataarts/v1.1/helpers.go
  acceptance/openstack/dataarts/v1/scripts_test.go
  openstack/client.go
  openstack/dataarts/v1/script/Create.go
  openstack/dataarts/v1/script/Delete.go
  openstack/dataarts/v1/script/Execute.go
  openstack/dataarts/v1/script/Get.go
  openstack/dataarts/v1/script/GetExecution.go
  openstack/dataarts/v1/script/List.go
  openstack/dataarts/v1/script/Stop.go
  openstack/dataarts/v1/script/Update.go
  openstack/dataarts/v1/script/common.go
Labels: enhancement, gate, post

#666 [FGS]: async config
  acceptance/openstack/fgs/v2/async_invoke_test.go
  openstack/fgs/v2/async_config/Delete.go
  openstack/fgs/v2/async_config/Get.go
  openstack/fgs/v2/async_config/Update.go
Labels: gate

#667 [DCS]: v2 lifecycle management
  acceptance/clients/clients.go
  acceptance/openstack/dcs/v2/helpers.go
  acceptance/openstack/dcs/v2/instance_test.go
  openstack/client.go
  openstack/dcs/v2/instance/Create.go
  openstack/dcs/v2/instance/Delete.go
  openstack/dcs/v2/instance/Get.go
  openstack/dcs/v2/instance/List.go
  openstack/dcs/v2/instance/Resize.go
  openstack/dcs/v2/instance/Update.go
  openstack/dcs/v2/others/ListAvailableZones.go
  openstack/dcs/v2/others/ListFlavors.go
Labels: gate

#668 [DCS]: v2 other APIs
  acceptance/openstack/dcs/v2/configs_test.go
  acceptance/openstack/dcs/v2/helpers.go
  acceptance/openstack/dcs/v2/instance_test.go
  acceptance/openstack/dcs/v2/ssl_test.go
  openstack/client.go
  openstack/dcs/v2/configs/Get.go
  openstack/dcs/v2/configs/Update.go
  openstack/dcs/v2/instance/Restart.go
  openstack/dcs/v2/instance/UpdatePassword.go
  openstack/dcs/v2/ssl/Get.go
  openstack/dcs/v2/ssl/Update.go
Labels: gate

#662 Implementation of DataArts Factory resources API
  acceptance/openstack/dataarts/v1/resources_test.go
  openstack/dataarts/v1/resource/Create.go
  openstack/dataarts/v1/resource/Delete.go
  openstack/dataarts/v1/resource/Get.go
  openstack/dataarts/v1/resource/List.go
  openstack/dataarts/v1/resource/Update.go
  openstack/dataarts/v1/resource/common.go
Labels: gate, post

#671 [APIGW] custom authorizer
  acceptance/openstack/apigw/v2/authorizer_test.go
  openstack/apigw/v2/authorizer/Create.go
  openstack/apigw/v2/authorizer/Delete.go
  openstack/apigw/v2/authorizer/Get.go
  openstack/apigw/v2/authorizer/List.go
  openstack/apigw/v2/authorizer/Update.go
Labels: enhancement, gate

#670 Implementation of DataArts Factory connections API
  acceptance/openstack/common.go
  acceptance/openstack/dataarts/v1.1/clusters_test.go
  acceptance/openstack/dataarts/v1.1/helpers.go
  acceptance/openstack/dataarts/v1.1/links_test.go
  acceptance/openstack/dataarts/v1/connections_test.go
  acceptance/openstack/dataarts/v1/resources_test.go
  openstack/dataarts/v1/connection/Create.go
  openstack/dataarts/v1/connection/Delete.go
  openstack/dataarts/v1/connection/Export.go
  openstack/dataarts/v1/connection/Get.go
  openstack/dataarts/v1/connection/List.go
  openstack/dataarts/v1/connection/Update.go
Labels: gate, post
