Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2024-12, with the labels that each got.

#764 [Feat.] gateway features endpoints
  acceptance/openstack/apigw/v2/gateway_test.go
  openstack/apigw/v2/gateway/ConfigureFeature.go
  openstack/apigw/v2/gateway/ListGatewayFeatures.go
  openstack/apigw/v2/gateway/ListSupportedFeatures.go
Labels: enhancement, gate

#763 OBS: acl for buckets
  acceptance/openstack/obs/v1/obs_test.go
  openstack/obs/client_bucket.go
  openstack/obs/convert.go
  openstack/obs/model_base.go
  openstack/obs/model_bucket.go
Labels: gate

#765 [Feat.] allow manual ci run for forked prs
  .github/workflows/ci.yaml
Labels: gate

#766 [Refactor] Refactor CCE v3 nodes
  .github/workflows/ci.yaml
  acceptance/openstack/cce/v1/nodes_test.go
  acceptance/openstack/cce/v3/nodes_test.go
  openstack/cce/v3/nodes/Create.go
  openstack/cce/v3/nodes/Delete.go
  openstack/cce/v3/nodes/Get.go
  openstack/cce/v3/nodes/Job.go
  openstack/cce/v3/nodes/List.go
  openstack/cce/v3/nodes/Update.go
  openstack/cce/v3/nodes/common.go
  openstack/cce/v3/nodes/requests.go
  openstack/cce/v3/nodes/testing/requests_test.go
  openstack/cce/v3/nodes/urls.go
Labels: gate

#768 OBS: Object acl and tests refactor
  acceptance/openstack/obs/v1/bucket/obs_acl_test.go
  acceptance/openstack/obs/v1/bucket/obs_bucket_test.go
  acceptance/openstack/obs/v1/bucket/obs_custom_domain_test.go
  acceptance/openstack/obs/v1/bucket/obs_inventory_test.go
  acceptance/openstack/obs/v1/bucket/obs_lifecycle_test.go
  acceptance/openstack/obs/v1/bucket/obs_policy_test.go
  acceptance/openstack/obs/v1/bucket/obs_replication_test.go
  acceptance/openstack/obs/v1/bucket/obs_worm_policy_test.go
  acceptance/openstack/obs/v1/object/obs_acl_test.go
  acceptance/openstack/obs/v1/obs_test.go
  openstack/obs/client_object.go
Labels: gate

#771 [Refactor] CCE: Refactor CCE Nodepools
  acceptance/openstack/cce/v3/nodepool_test.go
  openstack/cce/v3/nodepools/Create.go
  openstack/cce/v3/nodepools/Delete.go
  openstack/cce/v3/nodepools/Get.go
  openstack/cce/v3/nodepools/List.go
  openstack/cce/v3/nodepools/Update.go
  openstack/cce/v3/nodepools/common.go
  openstack/cce/v3/nodepools/requests.go
  openstack/cce/v3/nodepools/urls.go
Labels: gate, refactor

#773 Bump golang.org/x/crypto from 0.17.0 to 0.31.0
  go.mod
  go.sum
Labels: gate

#774 DCS: fix whitelist PUT response
  openstack/dcs/v2/whitelists/Put.go
Labels: gate

#776 [Remove] codeowners
  CODEOWNERS
Labels: gate

#775 [Refactor] CCE: Refactor CCE addons
  acceptance/openstack/cce/v3/addons_test.go
  openstack/cce/v3/addons/Create.go
  openstack/cce/v3/addons/Delete.go
  openstack/cce/v3/addons/Get.go
  openstack/cce/v3/addons/GetTemplates.go
  openstack/cce/v3/addons/ListAddonInstances.go
  openstack/cce/v3/addons/ListTemplates.go
  openstack/cce/v3/addons/Update.go
  openstack/cce/v3/addons/WaitCompleteion.go
  openstack/cce/v3/addons/common.go
  openstack/cce/v3/addons/requests.go
  openstack/cce/v3/addons/results.go
  openstack/cce/v3/addons/urls.go
Labels: gate, refactor

#754 Css updates
  acceptance/openstack/css/v1/change_cluser_name_test.go
  acceptance/openstack/css/v1/change_password_test.go
  acceptance/openstack/css/v1/cluster_add_nodes_test.go
  acceptance/openstack/css/v1/cluster_scale_in_test.go
  acceptance/openstack/css/v1/cluster_update_flavor_test.go
  acceptance/openstack/css/v1/cluster_update_sg_test.go
  acceptance/openstack/css/v1/cluster_update_sm_test.go
  acceptance/openstack/css/v1/restart_cluster_test.go
  openstack/css/v1/clusters/AddClusterNodes.go
  openstack/css/v1/clusters/ChangeClusterName.go
  openstack/css/v1/clusters/ChangePassword.go
  openstack/css/v1/clusters/RestartCluster.go
  openstack/css/v1/clusters/ScaleInCluster.go
  openstack/css/v1/clusters/UpdateClusterFlavor.go
  openstack/css/v1/clusters/UpdateSecurityGroup.go
  openstack/css/v1/clusters/UpdateSecurityMode.go
  openstack/css/v1/clusters/util.go
Labels: gate
