Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2024-10, with the labels that each got.

#727 [Refactor] Refactor SDRS Protected Instances
  .gitignore
  acceptance/openstack/sdrs/v1/protectedinstances_test.go
  openstack/sdrs/v1/protectedinstances/Create.go
  openstack/sdrs/v1/protectedinstances/Delete.go
  openstack/sdrs/v1/protectedinstances/Get.go
  openstack/sdrs/v1/protectedinstances/List.go
  openstack/sdrs/v1/protectedinstances/Update.go
  openstack/sdrs/v1/protectedinstances/requests.go
  openstack/sdrs/v1/protectedinstances/results.go
  openstack/sdrs/v1/protectedinstances/results_job.go
  openstack/sdrs/v1/protectedinstances/urls.go
Labels: gate

#729 [Fix] Fix SDRS Update Protected Instances
  acceptance/openstack/sdrs/v1/protectedinstances_test.go
  openstack/sdrs/v1/protectedinstances/Update.go
Labels: gate

#734 [Feat.] Enterprise VPN Connection Monitoring and EVPN Tags
  acceptance/openstack/evpn/connection_test.go
  openstack/evpn/v5/connection-monitoring/Create.go
  openstack/evpn/v5/connection-monitoring/Delete.go
  openstack/evpn/v5/connection-monitoring/Get.go
  openstack/evpn/v5/connection-monitoring/List.go
  openstack/evpn/v5/gateway/Create.go
  openstack/evpn/v5/quota/Get.go
  openstack/evpn/v5/tags/Create.go
  openstack/evpn/v5/tags/Delete.go
  openstack/evpn/v5/tags/List.go
Labels: enhancement, gate

#735 [Fix] Enterprise VPN Gateway fix response types
  openstack/evpn/v5/gateway/Create.go
Labels: bug, gate

#736 DMS: smart connect
  acceptance/openstack/dms/v2/instances_smart_connect_test.go
  acceptance/openstack/dms/v2/instances_test.go
  openstack/dms/v2/smart_connect/CreateTask.go
  openstack/dms/v2/smart_connect/DeleteTask.go
  openstack/dms/v2/smart_connect/Disable.go
  openstack/dms/v2/smart_connect/Enable.go
  openstack/dms/v2/smart_connect/GetTask.go
  openstack/dms/v2/smart_connect/ListTasks.go
  openstack/dms/v2/smart_connect/PauseTask.go
  openstack/dms/v2/smart_connect/RestartTask.go
  openstack/dms/v2/smart_connect/StartOrRestartTask.go
Labels: gate

#732 [Feat.] Add AS Lifecycle Hook
  acceptance/openstack/autoscaling/helpers.go
  acceptance/openstack/autoscaling/v1/lifecycle_hooks_test.go
  openstack/autoscaling/v1/lifecycle_hooks/Common.go
  openstack/autoscaling/v1/lifecycle_hooks/Create.go
  openstack/autoscaling/v1/lifecycle_hooks/Delete.go
  openstack/autoscaling/v1/lifecycle_hooks/Get.go
  openstack/autoscaling/v1/lifecycle_hooks/List.go
  openstack/autoscaling/v1/lifecycle_hooks/Update.go
Labels: enhancement, gate

#737 [Fix] Fix required param in AS group create
  acceptance/openstack/autoscaling/v1/groups_test.go
  openstack/autoscaling/v1/groups/create.go
Labels: gate

#738 CCE: node pool changes
  openstack/cce/v3/clusters/results.go
  openstack/cce/v3/nodepools/requests.go
  openstack/cce/v3/nodepools/results.go
Labels: gate

#740 [Feat.] RMS query endpoints and tests
  acceptance/clients/clients.go
  acceptance/openstack/rms/v1/query_test.go
  acceptance/tools/tools.go
  openstack/client.go
  openstack/css/v1/clusters/Create.go
  openstack/rms/query/GetAnyResource.go
  openstack/rms/query/GetCount.go
  openstack/rms/query/GetRecordedResource.go
  openstack/rms/query/GetResource.go
  openstack/rms/query/ListAllResources.go
  openstack/rms/query/ListAllResourcesTags.go
  openstack/rms/query/ListRecordeResourceTags.go
  openstack/rms/query/ListRecordedResources.go
  openstack/rms/query/ListRecordedResourcesSummary.go
  openstack/rms/query/ListResourcesSummary.go
  openstack/rms/query/ListServices.go
  openstack/rms/query/ListSpecificType.go
Labels: enhancement, gate

#741 RMS: recorder & relation api
  acceptance/openstack/rms/v1/history_test.go
  acceptance/openstack/rms/v1/recorder_test.go
  acceptance/openstack/rms/v1/relations_test.go
  openstack/rms/history/ListChangeRecords.go
  openstack/rms/recorder/DeleteRecorder.go
  openstack/rms/recorder/GetRecorder.go
  openstack/rms/recorder/UpdateRecorder.go
  openstack/rms/relations/ListRelations.go
Labels: gate

#742 RMS: Compliance api
  acceptance/openstack/rms/v1/compliance_test.go
  openstack/rms/compliance/AddRule.go
  openstack/rms/compliance/DeleteRule.go
  openstack/rms/compliance/DisableRule.go
  openstack/rms/compliance/EnableRule.go
  openstack/rms/compliance/GetPolicy.go
  openstack/rms/compliance/GetRule.go
  openstack/rms/compliance/GetRuleStatus.go
  openstack/rms/compliance/ListAllPolicies.go
  openstack/rms/compliance/ListAllRuleCompliance.go
  openstack/rms/compliance/ListAllUserCompliance.go
  openstack/rms/compliance/ListResCompliance.go
  openstack/rms/compliance/ListRules.go
  openstack/rms/compliance/RunEval.go
  openstack/rms/compliance/UpdateCompliance.go
  openstack/rms/compliance/UpdateRule.go
Labels: gate

#743 RMS: advanced queries
  acceptance/openstack/rms/v1/advanced_queries_test.go
  acceptance/openstack/rms/v1/regions_test.go
  openstack/rms/advanced/CreateQuery.go
  openstack/rms/advanced/DeleteQuery.go
  openstack/rms/advanced/GetQuery.go
  openstack/rms/advanced/ListQueries.go
  openstack/rms/advanced/ListSchemas.go
  openstack/rms/advanced/RunQuery.go
  openstack/rms/advanced/UpdateQuery.go
  openstack/rms/region/GetRegions.go
Labels: gate

#719 [Feat.] DirectConnect V3 implementation
  acceptance/clients/clients.go
  acceptance/openstack/dcaas/v3/hosted_connect_test.go
  acceptance/openstack/dcaas/v3/virtual_gateway_test.go
  acceptance/openstack/dcaas/v3/virtual_interface_test.go
  openstack/client.go
  openstack/dcaas/v3/hosted-connect/Create.go
  openstack/dcaas/v3/hosted-connect/Delete.go
  openstack/dcaas/v3/hosted-connect/Get.go
  openstack/dcaas/v3/hosted-connect/List.go
  openstack/dcaas/v3/hosted-connect/Update.go
  openstack/dcaas/v3/virtual-gateway/Create.go
  openstack/dcaas/v3/virtual-gateway/Delete.go
  openstack/dcaas/v3/virtual-gateway/Get.go
  openstack/dcaas/v3/virtual-gateway/List.go
  openstack/dcaas/v3/virtual-gateway/Update.go
  openstack/dcaas/v3/virtual-interface/Create.go
  openstack/dcaas/v3/virtual-interface/CreatePeer.go
  openstack/dcaas/v3/virtual-interface/Delete.go
  openstack/dcaas/v3/virtual-interface/DeletePeer.go
  openstack/dcaas/v3/virtual-interface/Get.go
  openstack/dcaas/v3/virtual-interface/List.go
  openstack/dcaas/v3/virtual-interface/Update.go
  openstack/dcaas/v3/virtual-interface/UpdatePeer.go
Labels: enhancement, gate

#744 IAM: All projects permissions for agencies
  acceptance/openstack/identity/v3.0/agency_test.go
  openstack/identity/v3.0/agency/CheckAgencyAllProjects.go
  openstack/identity/v3.0/agency/GrantAgenctAllProjects.go
  openstack/identity/v3.0/agency/ListAgencyAllProjects.go
  openstack/identity/v3.0/agency/RemoveAgencyAllProjects.go
Labels: gate
