Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2025-01, with the labels that each got.

#779 [Fix] HSS event response fix
  acceptance/openstack/hss/v5/event_test.go
  openstack/hss/v5/event/List.go
Labels: bug, gate

#785 CI update again
  .github/workflows/ci.yaml
Labels: gate

#784 [CCE]: implement az for master nodes
  acceptance/openstack/cce/helpers.go
  openstack/cce/v3/clusters/common.go
Labels: gate

#787 [Fix] DMS: Fix DMS Init Partition Reassigning
  acceptance/openstack/dms/v2/instances_management_test.go
  openstack/dms/v2/instances/management/InitPartitionReassigning.go
Labels: gate, fix
