Repository opentelekomcloud/gophertelekomcloud, pull requests merged in 2025-03, with the labels that each got.

#794 [Fix] Fix skip CFW EIP test
  acceptance/openstack/cfw/eip/eip_test.go
Labels: gate, fix

#793 RDS: Fix attach method
  acceptance/openstack/rds/v3/helpers.go
  acceptance/openstack/rds/v3/rds_test.go
  openstack/rds/v3/instances/AttachEip.go
Labels: gate

#797 [Fix] CI rollback rules
  .github/workflows/ci.yaml
Labels: gate, fix

#798 [Feat.] ER tags endpoints
  acceptance/openstack/er/router_test.go
  acceptance/openstack/lts/v2/lts_test.go
  openstack/er/v3/tags/Create.go
  openstack/er/v3/tags/Delete.go
  openstack/er/v3/tags/List.go
Labels: enhancement, gate

#795 [Feat.] CFW: Add CFW ACL rule management APIs
  acceptance/openstack/cfw/acl/acl_test.go
  acceptance/openstack/cfw/management/firewall_test.go
  openstack/cfw/v1/acl/Common.go
  openstack/cfw/v1/acl/Create.go
  openstack/cfw/v1/acl/Delete.go
  openstack/cfw/v1/acl/Get.go
  openstack/cfw/v1/acl/List.go
  openstack/cfw/v1/acl/SetRulePriority.go
  openstack/cfw/v1/acl/Update.go
  openstack/cfw/v1/eip/List.go
Labels: enhancement, gate

#799 [Feat.] CFW: Add CFW blacklist whitelist APIs
  acceptance/openstack/cfw/blackwhitelist/blackwhitelist_test.go
  openstack/cfw/v1/blackwhitelist/Common.go
  openstack/cfw/v1/blackwhitelist/Create.go
  openstack/cfw/v1/blackwhitelist/Delete.go
  openstack/cfw/v1/blackwhitelist/GetBlackWhiteList.go
  openstack/cfw/v1/blackwhitelist/GetBlackWhiteListRule.go
  openstack/cfw/v1/blackwhitelist/Update.go
Labels: gate

#802 [Feat.] ER Flow Logs
  acceptance/openstack/er/flow_logs_test.go
  openstack/er/v3/flow-logs/Create.go
  openstack/er/v3/flow-logs/Delete.go
  openstack/er/v3/flow-logs/Disable.go
  openstack/er/v3/flow-logs/Enable.go
  openstack/er/v3/flow-logs/Get.go
  openstack/er/v3/flow-logs/List.go
  openstack/er/v3/flow-logs/Update.go
Labels: enhancement, gate

#803 [Fix] ER Flow Logs Description update
  acceptance/openstack/er/flow_logs_test.go
  openstack/er/v3/flow-logs/Update.go
Labels: bug, gate

#805 [CCI]: configmap
  acceptance/openstack/cci/v2/configmap_test.go
  acceptance/openstack/cci/v2/namespace_test.go
  openstack/cci/v2/configmap/Create.go
  openstack/cci/v2/configmap/Delete.go
  openstack/cci/v2/configmap/Get.go
  openstack/cci/v2/configmap/List.go
  openstack/cci/v2/configmap/Update.go
  openstack/cci/v2/configmap/common.go
Labels: gate

#804 [Feat.] CFW: Add CFW address group management APIs
  acceptance/openstack/cfw/addressgroup/addressgroup_test.go
  openstack/cfw/v1/addressgroup/AddGroupMember.go
  openstack/cfw/v1/addressgroup/Common.go
  openstack/cfw/v1/addressgroup/CreateAddressGroup.go
  openstack/cfw/v1/addressgroup/DeleteAddressGroup.go
  openstack/cfw/v1/addressgroup/DeleteGroupMember.go
  openstack/cfw/v1/addressgroup/GetAddressGroup.go
  openstack/cfw/v1/addressgroup/GetGroupMember.go
  openstack/cfw/v1/addressgroup/ListAddressGroups.go
  openstack/cfw/v1/addressgroup/ListGroupMembers.go
  openstack/cfw/v1/addressgroup/UpdateAddressGroup.go
Labels: gate

#806 [Feat.] Refactoring and update LTS resources
  acceptance/openstack/er/flow_logs_test.go
  acceptance/openstack/fgs/v2/trigger_test.go
  acceptance/openstack/lts/v2/lts_test.go
  acceptance/openstack/lts/v2/lts_transfer_test.go
  openstack/lts/v2/groups/Create.go
  openstack/lts/v2/groups/Delete.go
  openstack/lts/v2/groups/List.go
  openstack/lts/v2/groups/Update.go
  openstack/lts/v2/streams/Create.go
  openstack/lts/v2/streams/Delete.go
  openstack/lts/v2/streams/List.go
  openstack/lts/v2/streams/Update.go
  openstack/lts/v2/transfers/Create.go
  openstack/lts/v2/transfers/Delete.go
  openstack/lts/v2/transfers/List.go
  openstack/lts/v2/transfers/Update.go
  openstack/lts/v2/transfers/UpdateTransfer.go
Labels: gate

#808 [Fix] add ttl_in_days in query response
  acceptance/openstack/lts/v2/lts_test.go
  openstack/lts/v2/streams/List.go
Labels: gate, fix

#807 [Feat.] CFW: Add CFW service group management APIs
  acceptance/openstack/cfw/servicegroup/servicegroup_test.go
  openstack/cfw/v1/servicegroup/AddGroupMember.go
  openstack/cfw/v1/servicegroup/Common.go
  openstack/cfw/v1/servicegroup/CreateServiceGroup.go
  openstack/cfw/v1/servicegroup/DeleteGroupMember.go
  openstack/cfw/v1/servicegroup/DeleteServiceGroup.go
  openstack/cfw/v1/servicegroup/GetGroupMember.go
  openstack/cfw/v1/servicegroup/GetServiceGroup.go
  openstack/cfw/v1/servicegroup/ListGroupMembers.go
  openstack/cfw/v1/servicegroup/ListServiceGroups.go
  openstack/cfw/v1/servicegroup/UpdateServiceGroup.go
Labels: enhancement, gate

#810 [Feat.] LTS Host Groups
  acceptance/clients/clients.go
  acceptance/openstack/lts/v2/lts_host_test.go
  openstack/client.go
  openstack/lts/v2/host-groups/Create.go
  openstack/lts/v2/host-groups/Delete.go
  openstack/lts/v2/host-groups/List.go
  openstack/lts/v2/host-groups/ListHost.go
  openstack/lts/v2/host-groups/Update.go
Labels: enhancement, gate

#812 [Fix] update fix
  acceptance/openstack/lts/v2/lts_host_test.go
  openstack/lts/v2/host-groups/Update.go
Labels: bug, gate
